name: store_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.3.4"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.15
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  font_awesome_flutter: ^9.0.0
  badges: ^2.0.1
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_svg: ^1.1.5
  image_picker: ^0.8.0+3
  google_sign_in: ^6.1.0
  dio: ^5.1.1
  flutter_secure_storage: ^8.0.0
  get_it: ^7.2.0
  path: ^1.8.2
  sqflite: ^2.2.0
  connectivity_plus: ^3.0.4
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  flutter_native_splash: ^2.2.16
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/carousels/
    - assets/images/logo/