// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE1cRSwRatFVmgxr1Gsi7v1F7MBcQDM2U',
    appId: '1:577764932911:web:9998c1daf92d9d803a75da',
    messagingSenderId: '577764932911',
    projectId: 'storeapp-f10dc',
    authDomain: 'storeapp-f10dc.firebaseapp.com',
    databaseURL: 'https://storeapp-f10dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'storeapp-f10dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Aw63Gs4aXr48z6p2UfwvjpKtvCyb1g8',
    appId: '1:577764932911:android:87d799e9fdd156f23a75da',
    messagingSenderId: '577764932911',
    projectId: 'storeapp-f10dc',
    databaseURL: 'https://storeapp-f10dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'storeapp-f10dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACYDBatJ7ayt6WzFnTuVHwOB4Th96jQuQ',
    appId: '1:577764932911:ios:ab0914a0a31524ae3a75da',
    messagingSenderId: '577764932911',
    projectId: 'storeapp-f10dc',
    databaseURL: 'https://storeapp-f10dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'storeapp-f10dc.appspot.com',
    androidClientId: '577764932911-1i34q1f9459ls36n9pmi52i3kk92vhrn.apps.googleusercontent.com',
    iosClientId: '577764932911-8hrsa6ad81gqdf17tdkp31m2ov82884q.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );
}
